package com.example.demoa.Enums;

public enum Status {
    OK,
    ERROR,
    NOT_FOUND,
    PERMISSION_DENIED,
    INTERNAL_SERVER_ERROR,
    PASSWORD_CHANGED,
    PASSWORD_NOT_CHANGED,
    PASSWORD_ATTEMPTED_CHANGE,
    USER_CREATE_ATTEMPTED,
    USER_DELETE_ATTEMPTED,
    USER_ADD_ATTEMPTED,
    USER_ITEM_ADD_ATTEMPTED,

}
